speaker: print speaker module information
Print speaker module related audio control items.
Test cases: Testrail C5373

Testing Done: test done on EVT1.2 and DB3.1

Change-Id: Ie07cf2c4f36388f746814a2c1d866e01fa53740e
Signed-off-by: Jason Hung <hung_jason@projectara.com>

diff --git a/apps/functional/spk_enum/spk_enum b/apps/functional/spk_enum/spk_enum
--- a/apps/functional/spk_enum/spk_enum
+++ b/apps/functional/spk_enum/spk_enum
@@ -1,3 +1,4 @@
+#!/system/bin/sh
 #
 # Copyright (c) 2016 Google, Inc.
 # All rights reserved.
@@ -26,18 +27,32 @@
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 
-include $(CURDIR)/../../../Makefile.inc
+#
+# Print audio module information(White speaker module)
+#
 
-APP=$(notdir $(CURDIR))
+CODEC=`cat /sys/kernel/debug/asoc/codecs | grep '[0-9]-[0-9][0-9]*\.[0-9]'`
 
-default: $(APP)
-	@mkdir -p $(APPOUTDIR)
-	@cp $(APP) $(APPOUTDIR)
+if [ -z $CODEC ]; then
+    echo "FAIL: audio module not found."
+    exit 1
+fi
 
-all: default
+echo "show audio module related mixer control:"
+for x in `tinymix | grep -e 'GB [0-9][0-9]*' -e 'PRI_MI2S_RX Audio Mixer MultiMedia1 ' | cut -f 1`
+do
+   tinymix $x
+done
 
-clean:
+echo ""
 
-.PHONY: all clean
+echo "show audio module related DAPM control:"
+DAPMDIR=/sys/kernel/debug/asoc/msm8994-tomtom-mtp-snd-card/$CODEC/dapm
+cd $DAPMDIR
+for f in *
+do
+    echo "[" $f "]"
+    cat "$f"
+done
 
-
+exit 0
